#!/bin/sh

# XDG Base Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# Zsh
export HISTFILE=${XDG_DATA_HOME}/zsh/history
HISTSIZE=100000
SAVEHIST=100000

# .local binaries
export PATH="$HOME/.local/bin":$PATH

# Disable files
export LESSHISTFILE=-

# Gtk
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

# NPM
export NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc

# VIM
export VIMINIT=":source $XDG_CONFIG_HOME"/vim/vimrc

# wget
export WGETRC=$XDG_CONFIG_HOME/wgetrc

# z
export _Z_DATA="$XDG_DATA_HOME/z"
[[ -r "/usr/share/z/z.sh" ]] && source /usr/share/z/z.sh

# asdf
. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath) # append asdf completions to fpath
fpath=(_btm $fpath) # append bottom completions to fpath

# Enviroment variables
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="firefox"

# For QT Themes
export QT_QPA_PLATFORMTHEME=qt5ct
